### ISSUE TITLE
Implementation of the derivatives of \gamma(u, v) in Eq (15)

### ISSUE THREAD

**Issue by Crane-YU** [rubenwiersma/deltaconv#2]
Hi @rubenwiersma,
Thx for sharing this excellent work.
While I was going through the paper details, I got confused by the implementation of $\partial_{u} \Gamma\left(u_{j}, v_{j}\right) \text{ and } \partial_{v} \Gamma\left(u_{j}, v_{j}\right)$ in these two lines [L173-174](https://github.com/rubenwiersma/deltaconv/blob/master/deltaconv/geometry/grad_div_mls.py#L173).
Why is the implementation different from that of grad? Can u plz give detailed mathematical expressions for this?

**Comment by rubenwiersma** [comment]
Hi @Crane-YU, thanks for your friendly comment and question! The difference between this mapping and that of the normal grad is (1) the function that the gradient is computed on and (2) where the gradient is evaluated.

In the network we use gradient to analyze the features at each point on the surface (a 2D manifold). We could write the map from points on the manifold $\mathcal{M}$ to the feature vector with $C$ channels:
$f: \mathcal{M} \rightarrow \mathbb{R}^C$.
The gradient then computes the directional derivative of  $f $. Because we compute the gradient on a patch centered at each point, the gradient is evaluated at $(0, 0)$.

In equation 15, we are trying to find how the basis vectors are transformed as they are moved along a small patch of surface $\mathbb{\Gamma}$
$\mathbb{\Gamma}: \mathbb{\Omega} \subset \mathbb{R}^2 \rightarrow \mathbb{R}^3$.

The derivative of  $\mathbb{\Gamma} $ tells us how vectors are transformed by  $\mathbb{\Gamma} $. That means we can evaluate  $\partial_u\mathbb{\Gamma}(u_j, v_j) $ to find out how the basis vector for $u$ is transformed at the *neighboring* point. The difference with the gradient used in the network is that we evaluate this derivate at  $(u_j, v_j) $ instead of at  $(0, 0) $.

The result of evaluating these derivatives:
- $\partial_u \Gamma(u_j, v_j) = [1, 0, h_u]^T$, $h_u$ is defined in Equation (3)
- $\partial_v \Gamma(u_j, v_j) = [0, 1, h_v]^T$, $h_v$ is defined in Equation (4)

Two differences in the code: $h_u$ and $h_v$ are `h_x` and `h_y`, respectively and I also include the linear components (`coefficients[row, 1]` and `coefficients[row, 2]`). This is not strictly necessary as the linear component should vanish, given that the patch of surface is 'aligned' to the tangent plane.

In [L173-174](https://github.com/rubenwiersma/deltaconv/blob/master/deltaconv/geometry/grad_div_mls.py#L173), I transform this derivative from coordinates with respect to the tangent plane to coordinates in 3D:
- `gamma_x`: $[\mathbf{e}^u, \mathbf{e}^v, \mathbf{n}] [1, 0, h_u]^T$,
- `gamma_y`: $[\mathbf{e}^u, \mathbf{e}^v, \mathbf{n}] [0, 1, h_v]^T$,

where  $\mathbf{e}^u $ and  $\mathbf{e}^v $ are the the basis vectors at the center point and  $\mathbf{n} $ is the normal at the center point.

I hope this helps! Feel free to ask more questions if it's still unclear.

**Comment by Crane-YU** [comment]
Hi @rubenwiersma, your explanation really helps. Thanks u so much.
