### ISSUE TITLE
coordinate-independency breaks when using xyz-coordinates as input 

### ISSUE THREAD

**Issue by David-Willo** [rubenwiersma/deltaconv#4]
Hi, thanks for your excellent work,
I do some simple tests feeding rotated point clouds into DeltaNetSegmentation
it seems  coordinate-independency breaks(output features are different) when using xyz-coordinates as input scalar field,
is it an expected behavior?
should we set constant values to each node to guarantee coordinate-independency?

here is my test code:
```
    # coordinate independent
    model = deltaconv.models.DeltaNetSegmentation(1, 256).to('cuda')
    # not coordinate independent
    # model = deltaconv.models.DeltaNetSegmentation(3, 256).to('cuda')
    torch.set_printoptions(precision=2, threshold=10)
    pos = torch.randn(100, 3).cuda() 
    batch_ids = torch.zeros(100).cuda().long()
    input = torch.ones(100,1).cuda()
    for R in RandomRotations():
        pos_r = pos @ R
        # coordinate independent
        feats = model(DataSeg(pos_r, batch_ids, input))
        # not coordinate independent
        # feats = model(DataSeg(pos_r, batch_ids))
        print(torch.sum(feats, dim=0).detach())
        print(feats[5:8].detach())
```

**Comment by rubenwiersma** [comment]
Hi David,

Thanks for reaching out! Yes, this is expected behavior. DeltaConv is indeed independent with regards to coordinate systems -- both local coordinate systems on the surface and the coordinate system in which the surface is embedded.

However, the tricky part is: if you use xyz-positions as input, the input also changes with rotations of the surface. The solution is to make sure that the input to the network is also coordinate independent. This is simple if your input is color: that's always rotation independent. But if you are using positions, the input is intertwined with your coordinate system.

There are works that specifically target this and they can be combined with DeltaConv, because everything apart from the input is coordinate-independent. For example: you can compute a Heat Kernel Signature for each point and feed it into DeltaConv. This is done by the authors of MDGCNN (Poulenard et al.) and DiffusionNet (Sharp et al.) and others. Another solution is to combine ideas from other papers that do work on rotation-independence of the input features and use those as a first layer, or use the input features they define (e.g., distance from the center, curvature).

Best,

Ruben

**Comment by David-Willo** [comment]
I see.
Thanks, Ruben. : )
